/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ayadatabase;

/**
 *
 * @author user
 */
public class LoginOrSignin extends javax.swing.JFrame {

    /**
     * Creates new form LoginOrSignin
     */
    public LoginOrSignin() {
        initComponents();


        setSize(1650, 1000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        button1.setBackground(new java.awt.Color(242, 242, 242));
        button1.setFont(new java.awt.Font("Rockwell", 1, 32)); // NOI18N
        button1.setForeground(new java.awt.Color(192, 141, 34));
        button1.setLabel("log in");
        jPanel1.add(button1);
        button1.setBounds(630, 710, 290, 70);

        button2.setBackground(new java.awt.Color(192, 141, 34));
        button2.setFont(new java.awt.Font("Rockwell", 1, 32)); // NOI18N
        button2.setForeground(new java.awt.Color(242, 242, 242));
        button2.setLabel("Sign Up");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        jPanel1.add(button2);
        button2.setBounds(630, 620, 290, 70);

        jLabel2.setFont(new java.awt.Font("Script MT Bold", 1, 45)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(192, 141, 34));
        jLabel2.setText("Welcome to Golden Beauty Salon");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(440, -40, 780, 190);

        jPanel2.setBackground(new java.awt.Color(192, 141, 34));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("More than just a golden salon,\n");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 60, 270, 60);

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setText(" Golden Beauty Salon ");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 110, 360, 43);

        jLabel3.setFont(new java.awt.Font("Segoe Print", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("golden Beauty salon?");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 10, 300, 70);

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setText("embodies the qualities and.");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(40, 150, 250, 40);

        jLabel7.setFont(new java.awt.Font("Segoe Print", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(242, 242, 242));
        jLabel7.setText(" attributes that its name suggests");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 190, 280, 29);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe Print", 0, 20)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(186, 120, 122));
        jTextArea1.setRows(5);
        jTextArea1.setText("Dear Customer to get golden services\n from golden Beauty Saoln \nyou should Follow our instructions\nGood experience in \nour salon!\n          (golde Beauty Saoln)");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(0, 300, 460, 290);

        jLabel9.setFont(new java.awt.Font("Segoe Print", 1, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(242, 242, 242));
        jLabel9.setText("Dear Customers");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 260, 190, 40);

        jButton1.setBackground(new java.awt.Color(242, 242, 242));
        jButton1.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(192, 141, 34));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(10, 680, 140, 60);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 410, 850);

        jPanel3.setBackground(new java.awt.Color(192, 141, 34));
        jPanel3.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Segoe Print", 1, 26)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(242, 242, 242));
        jLabel8.setText("Discounts ! : ");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(10, 470, 210, 47);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe Print", 0, 22)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(186, 120, 122));
        jTextArea2.setRows(5);
        jTextArea2.setText("Discount in Golden Beauty Salon\nGolden memmberShip : 50%\nSilver memmberShip : 30%\nBronze memmberShip : 20%\n\n       Booked Appointment Now!");
        jScrollPane2.setViewportView(jTextArea2);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(0, 520, 484, 267);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(1130, 20, 440, 850);

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\G.png")); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(460, 190, 490, 390);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1700, 850);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
       
    }//GEN-LAST:event_button2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
       BeautySaoln B=new BeautySaoln();
       B.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginOrSignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginOrSignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginOrSignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginOrSignin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginOrSignin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
